# Infisical Self-Hosted - Ready-to-Use Manifests
# ================================================
# 
# Instructions:
# 1. Replace all <PLACEHOLDER> values with your actual values
# 2. Apply in order: namespace → secrets → helm install → operator → CRDs

---
# File: 01-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: infisical

---
# File: 02-infisical-secrets.yaml
# Required secrets for Infisical deployment
# Generate keys with:
#   ENCRYPTION_KEY=$(openssl rand -hex 16)
#   AUTH_SECRET=$(openssl rand -base64 32)
apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: infisical
type: Opaque
stringData:
  # REQUIRED: 32-character hex string for encrypting data at rest
  ENCRYPTION_KEY: "<GENERATE_WITH_openssl_rand_-hex_16>"
  
  # REQUIRED: Secret for signing auth tokens
  AUTH_SECRET: "<GENERATE_WITH_openssl_rand_-base64_32>"
  
  # REQUIRED: Public URL where Infisical will be accessed
  SITE_URL: "https://infisical.example.com"
  
  # OPTIONAL: For production, use external PostgreSQL
  # DB_CONNECTION_URI: "postgresql://user:pass@host:5432/infisical?sslmode=require"
  
  # OPTIONAL: For production, use external Redis
  # REDIS_URL: "redis://:password@host:6379"

---
# File: 03-values.yaml (save separately for Helm)
# This is a reference - save as values.yaml and use with helm install
#
# nameOverride: "infisical"
# fullnameOverride: "infisical"
# 
# infisical:
#   enabled: true
#   replicaCount: 2
#   image:
#     repository: infisical/infisical
#     tag: "v0.91.0-postgres"
#     pullPolicy: IfNotPresent
#   kubeSecretRef: "infisical-secrets"
#   resources:
#     limits:
#       memory: 512Mi
#     requests:
#       cpu: 200m
#       memory: 256Mi
# 
# ingress:
#   enabled: true
#   hostName: "infisical.example.com"
#   ingressClassName: nginx
#   nginx:
#     enabled: true
#   tls:
#     - secretName: infisical-tls
#       hosts:
#         - infisical.example.com
# 
# postgresql:
#   enabled: true
#   fullnameOverride: "postgresql"
#   auth:
#     username: infisical
#     password: "<CHANGE_THIS_PASSWORD>"
#     database: infisicalDB
# 
# redis:
#   enabled: true
#   fullnameOverride: "redis"
#   architecture: standalone
#   auth:
#     enabled: true
#     password: "<CHANGE_THIS_PASSWORD>"

---
# File: 04-operator-global-config.yaml
# Optional: Configure defaults for all InfisicalSecret CRDs
apiVersion: v1
kind: Namespace
metadata:
  name: infisical-operator-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infisical-config
  namespace: infisical-operator-system
data:
  # Default API endpoint - update with your Infisical URL
  hostAPI: "https://infisical.example.com/api"

---
# File: 05-universal-auth-credentials.yaml
# Store machine identity credentials for the operator
# Get these from Infisical UI: Organization Settings → Machine Identities
apiVersion: v1
kind: Secret
metadata:
  name: universal-auth-credentials
  namespace: default  # Change to your application namespace
type: Opaque
stringData:
  clientId: "<YOUR_MACHINE_IDENTITY_CLIENT_ID>"
  clientSecret: "<YOUR_MACHINE_IDENTITY_CLIENT_SECRET>"

---
# File: 06-infisical-secret-example.yaml
# Example InfisicalSecret CRD to sync secrets from Infisical to K8s
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: my-app-secrets
  namespace: default  # Change to your application namespace
  labels:
    app: my-app
spec:
  # Your self-hosted Infisical API endpoint
  hostAPI: https://infisical.example.com/api
  
  # Sync interval in seconds
  resyncInterval: 60
  
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: default  # Same namespace as credentials secret
      secretsScope:
        # Your Infisical project slug (from URL: /project/<slug>/...)
        projectSlug: "<YOUR_PROJECT_SLUG>"
        # Environment: dev, staging, prod, etc.
        envSlug: "prod"
        # Path within the project (root is "/")
        secretsPath: "/"
        # Include secrets from subfolders
        recursive: true
  
  managedSecretReference:
    # Name of the K8s Secret that will be created/managed
    secretName: my-app-managed-secret
    secretNamespace: default
    # Owner = delete secret when CRD deleted, Orphan = keep secret
    creationPolicy: Owner

---
# File: 07-deployment-example.yaml
# Example deployment consuming the managed secret
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
  annotations:
    # Enable auto-restart when secret changes
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: nginx:alpine  # Replace with your image
          ports:
            - containerPort: 80
          # Option 1: Load all secrets as env vars
          envFrom:
            - secretRef:
                name: my-app-managed-secret
          # Option 2: Load specific secrets
          # env:
          #   - name: DATABASE_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: my-app-managed-secret
          #         key: DATABASE_PASSWORD

---
# File: 08-infisical-secret-with-template.yaml
# Advanced example with secret templating
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: my-app-templated-secrets
  namespace: default
spec:
  hostAPI: https://infisical.example.com/api
  resyncInterval: 60
  
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: default
      secretsScope:
        projectSlug: "<YOUR_PROJECT_SLUG>"
        envSlug: "prod"
        secretsPath: "/"
  
  managedSecretReference:
    secretName: my-app-config
    secretNamespace: default
    creationPolicy: Owner
  
  # Use templating to transform/combine secrets
  template:
    includeAllSecrets: false
    data:
      # Combine multiple secrets into a connection string
      DATABASE_URL: "postgresql://{{ .DB_USER.Value }}:{{ .DB_PASSWORD.Value }}@{{ .DB_HOST.Value }}:5432/{{ .DB_NAME.Value }}"
      
      # Create a JSON config
      CONFIG_JSON: |
        {
          "api_key": "{{ .API_KEY.Value }}",
          "environment": "production",
          "debug": false
        }
      
      # Direct mapping with rename
      SECRET_KEY: "{{ .APP_SECRET.Value }}"

---
# File: 09-kubernetes-auth-setup.yaml
# For Kubernetes-native auth (no static credentials)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infisical-auth-reviewer
  namespace: infisical-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infisical-auth-reviewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: infisical-auth-reviewer
    namespace: infisical-operator-system
---
# Service account for your app to authenticate with Infisical
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-app-sa
  namespace: default

---
# File: 10-infisical-secret-k8s-auth.yaml
# InfisicalSecret using Kubernetes auth instead of static credentials
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: my-app-secrets-k8s-auth
  namespace: default
spec:
  hostAPI: https://infisical.example.com/api
  resyncInterval: 60
  
  authentication:
    kubernetesAuth:
      # Machine Identity ID from Infisical (configured with K8s auth)
      identityId: "<YOUR_MACHINE_IDENTITY_ID>"
      serviceAccountRef:
        name: my-app-sa
        namespace: default
      secretsScope:
        projectSlug: "<YOUR_PROJECT_SLUG>"
        envSlug: "prod"
        secretsPath: "/"
        recursive: true
  
  managedSecretReference:
    secretName: my-app-managed-secret-k8s-auth
    secretNamespace: default
    creationPolicy: Owner
